### ISSUE TITLE
Front-end stack

### ISSUE THREAD

**Issue by vramana** [fcc-hyd/fcc-hyd#1]
If we want to use React, I will suggest using create-react-app. What are your suggestions? 

If people are feeling wild to try out new stuff, may be clojurescript and om-next? Elm?

@chakrihacker @duttakapil  

Please tag others who may be interested.

**Comment by duttakapil** [comment]
React is fine by me. Regarding trying new stuff like Elm, we can build side projects with them later on

**Comment by vramana** [comment]
Create-react-app then.

**Comment by vinaypuppal** [comment]
How about using [Next.js](https://github.com/zeit/next.js/) instead of Create-React-App??

cc @vramana @duttakapil

**Comment by vramana** [comment]
It has lots of nice defaults. So, I am okay with anything.

**Comment by chakrihacker** [comment]
I don't know React but just made a search about next.js and create react app, I found this link [http://andrewhfarmer.com/create-react-app/](create react) @vinaypuppal my only question is will next.js is easy for beginners to understand and help to contribute, On the other side *Create-React-app* is popular

**Comment by vinaypuppal** [comment]
@chakrihacker Few things to be clear at first
**Create-React-App** 
- it is just a CLI tool to create boilerplate code for React apps i.e generate default folder structure, build tool setup(webpack)
- so we can quick start the project easily

**Next.js**
- its a minimal framework for creating universal react apps i.e server side rendered React apps
- it also takes care about build step
- the interesting part in next.js is routing, it uses filesystem as router i,e it uses `pages/` folder and each file in this folder is serverd as new route(/page) (somewhat like old traditional PHP server)
- You can read more here https://zeit.co/blog/next
- if you want examples, there are many examples here https://github.com/zeit/next.js/tree/master/examples

Both has nothing to do with learning/using React, we just write React components in both but we have to use ReactRouter for client side routing if we use Create-React-App whereas in Next.js `pages/` folder create routes for us.

**Comment by chakrihacker** [comment]
I am ok with next.js

**Comment by duttakapil** [comment]
Can you guys explain to me how exactly will creat-react-app or Next.js come into play in our development? Right now, our immediate task after merging Vinay's PR is to work on the registration, maintaining user profiles and then re-building the Members List with search and filtering features. 
Based on this, how are we going to use either of the two? 
@vinaypuppal @vramana

**Comment by vinaypuppal** [comment]
@duttakapil If we want to use React.js then we should not merge my PR instead we should port the new layout to React.js using either CRA or Next.js so the workflow for building additional features will be easy.

Regarding CRA or Next.js i will leave final decision to @vramana

**Comment by vramana** [comment]
Next.js is the preferable choice here. Although CRA can be used to write production applications, next.js edges CRA because you get SSR + SW for free.

**Comment by duttakapil** [comment]
Fine, let's ditch the PR and start over then

**Comment by duttakapil** [comment]
Let's use this [C9 Workstation](https://ide.c9.io/duttakapil/fcc-hyd) for building the site?

**Comment by vinaypuppal** [comment]
@chakrihacker some [Starter and Inspiration project links built](https://github.com/zeit/next.js/issues/727) using Next.js

**Comment by chakrihacker** [comment]
@vramana what is ssr + sw??

**Comment by chakrihacker** [comment]
decided to use next.js

**Comment by vramana** [comment]
Server Side Rendering + Service Workers
