### ISSUE TITLE
Merge new-interface branch into master?

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/fcc-hyd#11]
Now that we have a basic landing page interface set, let's merge the `new-interface` branch into `master`? We can then start creating issues for features and sharing them with the community.

**Comment by vinaypuppal** [comment]
The banner image looks odd and heavy in color to me, i wanted to change it before merging it to master                        
Do you have any alternative images??                        
If you want to do this POST merge send a PR for merging
