### ISSUE TITLE
Change banner image

### ISSUE THREAD

**Issue by vinaypuppal** [fcc-hyd/fcc-hyd#13]
- The banner image looks odd and heavy in color to me

**Comment by duttakapil** [comment]
What labels should you suggest for this issue? `ui`? `ui/ux`?

**Comment by vinaypuppal** [comment]
How about a banner image like 👇  but with monuments or buildings from hyderabad
![screen shot 2017-03-13 at 12 40 14 am](https://cloud.githubusercontent.com/assets/8843216/23835036/2a6c1a74-0786-11e7-9242-27c57133227b.png)

**Comment by vinaypuppal** [comment]
@duttakapil why did you close this??

**Comment by duttakapil** [comment]
We'll reopen it again, once we make some significant progress with the website

**Comment by vinaypuppal** [comment]
@duttakapil okay but from next time please mention why are you closing an issue before closing it.
