### ISSUE TITLE
Make new interface responsive for different screen sizes

### ISSUE THREAD

**Issue by vinaypuppal** [fcc-hyd/fcc-hyd#14]
- Need to add few media queries to make the site responsive and usable for every screensize
PR's are welcomed!

**Comment by duttakapil** [comment]
What labels should you suggest for this issue?
My suggestions : `ux`, `ui/ux`, `user-experience`, `design`

**Comment by harishkotra** [comment]
Bootstrap is almost the new standard for websites/web apps. Why isn't this on bootstrap?

**Comment by duttakapil** [comment]
Hey @harishkotra, this doesn't use bootstrap right now simply because I'm not used to using it. Anyone willing to contribute to this issue is free to use bootstrap

**Comment by vinaypuppal** [comment]
@harishkotra 
I am not against bootstrap or any other css framework but my question is why we need a css framework?? 
- oh for grids(we can use flexbox), 
- oh for responsivesness(we can write our own media queries), 
- oh for components(It will be more fun developing these ourselves, any way we dont like default bootstrap styles and we ultimately overide them to suit our needs withour own css after adding bootstrap classes then why to use them while we can write them from scratch as we want and learn new things). 

This way we can learn new css techniques and tricks. 

## But How??
If we want to implement some component eg:Bootstrap Navbar, then try to look at source code of bootstrap and try to implement it from scratch, I know we should not reinvent a wheel but for learning the underlaying parts we can reinvent it.
These are reasons why me and @duttakapil  decided to go with Vanilla css and js(we decided not even use JQuery :smile:)

For reference I built this old FCC layout without any css framework, is this not responsive or good (https://fcc-hyd.surge.sh/)

**Comment by rrmerugu** [comment]
@vinaypuppal  I see what you are talking about. But if you think bootstrap is too much of a framework for a static website like us now ? (Yes, it is as far I believe). We can create a custom build of bootstrap with just the few components that we use. Here is the link to do that http://getbootstrap.com/customize/ . **But I believe, established framework like bootstrap gives us good advantage when we are going beyond this state of the website - Imean scaling the product to more design complexity can be quick** . More UI components, can be leveraged. We can still start with vanilla, but I think we wind up building our framework if we do that  😄 . I wish we can build a new and light framework too ;)

**Comment by vinaypuppal** [comment]
> I wish we can build a new and light framework too ;)

@rrmerugu Yeah exactly we can build small components and share them across all the projects in this organization. 
The only thing i want to convey is we are here to learn and  frameworks abstracts learning these underlying parts. It's not a site we build for a company. So learning should be our top priority.
