### ISSUE TITLE
Structure to organise the static assets

### ISSUE THREAD

**Issue by rrmerugu** [fcc-hyd/fcc-hyd#16]
Currently there is not file structure. Why don't we structure it to something like this !

```
static/
         images/
         scripts/ # for js files
         styles/ # for css files
  
```

**Comment by vramana** [comment]
When you have handful of resources, does it even matter? If you want to create a PR, go for it. IMHO there better things one can focus on.

**Comment by duttakapil** [comment]
Agree with @vramana here

**Comment by rrmerugu** [comment]
@duttakapil  @vramana  True, thats the reason I asked you guys to mark it enhancement :)
