### ISSUE TITLE
Our immediate plan for new website [Updated]

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/fcc-hyd#2]
Technologies we'll use : 
- React JS ([Next.js](https://github.com/zeit/next.js/))
- Firebase (Authentication and Database)
- https://now.sh (Hosting)

Immediate Plan : 
- We'll first officially push @vinaypuppal's [new interface for our website](http://fcc.now.sh/) ([source code](https://github.com/vinaypuppal/fcc-hyd.github.io/tree/redesigned))
- We'll then move our site to Now.sh officially
- To make the site dynamic, we'll start with the [Members List](http://fcc-hyd.github.io/members). We'll have a registration process, and maintain member profiles in Firebase, then display them on our website using React. 
- Since all of us have a C9 account, we can collaborate on it for building the new site. For prototyping simple ideas, we'll use GoMix
- Next will come features like being able to filter members based on the technologies they are good at, our own email system to send everyone important emails/reminders etc
- We'll use [this GitHub Project](https://github.com/fcc-hyd/fcc-hyd/projects/1) to keep track of the new website development

This is a good enough immediate plan for now

Discuss : 
- Should we have a separate repo for the members list, the jobs board and the projects page? 

For any questions or suggestions, comment below

**Comment by vramana** [comment]
What exactly is ZenKit for? Can't we use Github projects instead?

**Comment by duttakapil** [comment]
@vramana I knew about GitHub Projects, but never tried it. Just [created a few columns](https://github.com/fcc-hyd/fcc-hyd/projects/1), and my immediate feedback is that its a decent Kanban system, you can create stages and move cards. But it's limited. 
Zenkit on the other hand is equal to Google Keep + Trello + Google Calendar + Airtable (+ Coggle soonish). 
It's far more powerful than anything else I've used till date. 
We can still use GitHub Projects for basic project management, if others feel like it's sufficient.

**Comment by vramana** [comment]
I refer you to Spectrum of Abstraction. It roughly says **"The more power an abstraction has the less useful it is"**. Do we need all that power at all?

**Comment by duttakapil** [comment]
Agreed. All that power is not necessarily needed in this case and at this time. A basic Kanban system built into GitHub should work just fine for now. We can go ahead with it. I will however continue to keep the Zenkit collection updated, along with other collections for the community, as I personally find it far better for keeping track of things.

**Comment by BosH9** [comment]
hi , how about the guys who dont have c9 accounts ? we need credit cards for it ....
so any alternative for this ?

**Comment by vramana** [comment]
We will push everything to this repo so, you can submit a PR against this repo too.

**Comment by duttakapil** [comment]
Change of mind for tech stack (up for discussion) : 

While I'm all for using interesting new technology (Next.js, even React), let's build the new site in pure vanilla, so as to make it much easier for others to contribute. We can use interesting libraries and frameworks for our side projects. We only get one shot at this, let's be considerate of all factors. 

We can still plug in React as we progress, starting with the member profiles and members list.

So the current suggested stack is 
- Frontend : HTML, CSS, JavaScript, 
- Authentication and Databse : Firebase, 
- Hosting : Now.sh

What do you guys think?

**Comment by vramana** [comment]
While you can think it will just be vanilla javascript, it will end up being more complexity in the code. You are only pushing complexity around and not eliminating it. So resulting code base will be harder to write maintain. Ofcourse this is not valid for 100 line javascript file. 

Honestly it doesn't matter to me what we use. Just make up your mind.

**Comment by duttakapil** [comment]
@vramana totally agree. As the complexity increases, we'll have the relevant use cases for plugging in React to make things simpler. Vanilla it is then
