### ISSUE TITLE
Mock ups and Wireframes for the new interface

### ISSUE THREAD

**Issue by vinaypuppal** [fcc-hyd/fcc-hyd#6]
As per the requirements mentioned in #4, we should come up with wireframes for each page

- [x] Landing Page - so far we have [this new layout](https://fcc-hyd-website.now.sh) 
- [x] Jobs Board - new layout or any improvements on https://fcc-hyd.github.io/jobs/
- [ ] Issues Page - new layout or any improvements on https://fcc-hyd.github.io/issues/ 
- [ ] Profile Page
- [x] Member List
- [x] Projects page 

We should also identify the **color palette**, **fonts**, ...etc i.e a **style guide**. For reference we can follow **FCC style guide** https://freecodecamp.github.io/design-style-guide/

As per the timeline mentioned in #5 we should come up with wireframe for **Landing Page** by **22nd Jan** so we can implement it the following week. 

@duttakapil tag designers in this community who may be interested.

**Comment by duttakapil** [comment]
@srichakradhar @sudheerdarla you guys might be able to get something started. We can do regular calls around 7 pm if needed. Deadline is 22nd Jan for the mockups

**Comment by vinaypuppal** [comment]
For creating basic wireframes we can use this tool http://quirktools.com/wires/ which is free for 3 projects. For advance mockups we can use https://www.invisionapp.com/ or any other tools which suits our needs.

**Comment by iampowerhouse** [comment]
I can create some mockups ..

**Comment by duttakapil** [comment]
Let's do a call tomorrow 7:30 pm to discuss this. @srichakradhar, @sudheerdarla and @iampowerhouse can join

**Comment by seenu511-hcl** [comment]
Hey Guys Good to see Lot of challenging tasks are ready!!! and i am happy to contribute into it.

**Comment by duttakapil** [comment]
Sure @seenu511-hcl. Everyone else, let's not forget the call we have to do today at 7:30 pm

**Comment by duttakapil** [comment]
Summary of call : 
- We have to finalize on the font, color theme, common components of the website
- @srtarun will be leading the user experience and design for the new website
- We have to merge the new interface by @vinaypuppal and then start contributing to it
- I'll be adding some more content to the site 
- 29th Jan is the deadline for announcing the new website
- We'll be doing these calls as frequently as possible

Please share any ideas, suggestions or questions you have

**Comment by duttakapil** [comment]
We have pushed the code : https://fcc-hyd.github.io/fcc-hyd/
Now we can create new issues and update as we go

**Comment by vinaypuppal** [comment]
Links discussed in hangout call
- http://berlinjs.org/
- http://js.la/
- https://www.thoughtworks.com/
- http://codeslo.com/
- https://twhyderabad.github.io/geeknight/
- http://www.thehackingschool.com/home/index.html
- http://icancode.in/
- http://www.codeastra.com/
- http://www.codingblocks.com/
- https://www.hackerearth.com/
- http://www.geekskool.com/
- http://www.codingninjas.in/
- https://acadgild.com/
- http://internstreet.in/
- https://www.42.us.org/
- https://www.recurse.com/
- http://www.hackreactor.com/
- http://get.aospa.co/
- http://mugh.net/
- https://devbootcamp.com
- https://www.meetup.com/hamburg-js/
- https://events.google.com/io2016/

**Comment by duttakapil** [comment]
Update : Checkout the prototype/wireframe we're working on for the new website : http://quirktools.com/wires/iydupe/?t=1

**Comment by vramana** [comment]
Needs a frigging account 😦

**Comment by duttakapil** [comment]
@vramana my bad. Fixed it

**Comment by vramana** [comment]
I's much simpler to write this in HTML itself.
